version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ambev_db
    environment:
      POSTGRES_DB: DeveloperEvaluation
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - "5005:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: